/** Semantic relationships ported from the proven Feed Search engine. Discovery hints only; Phase 2 validates URLs. */
const TOPIC_GRAPH = {
  news: { neighbors: ['world news', 'headlines', 'geopolitics', 'international affairs'], sources: [['BBC News World', 'https://feeds.bbci.co.uk/news/world/rss.xml', 'https://www.bbc.com/news/world', 'News'], ['The Guardian World News', 'https://www.theguardian.com/world/rss', 'https://www.theguardian.com/world', 'News'], ['Sky News World', 'https://feeds.skynews.com/feeds/rss/world.xml', 'https://news.sky.com/world', 'News']] },
  'world news': { neighbors: ['global news', 'international breaking news', 'geopolitics', 'foreign affairs'], sources: [['BBC News World', 'https://feeds.bbci.co.uk/news/world/rss.xml', 'https://www.bbc.com/news/world', 'News'], ['The Guardian World News', 'https://www.theguardian.com/world/rss', 'https://www.theguardian.com/world', 'News']] },
  science: { neighbors: ['space exploration', 'nasa', 'astronomy', 'physics', 'biotech', 'climate science'], sources: [['NASA Breaking News', 'https://www.nasa.gov/rss/dyn/breaking_news.rss', 'https://www.nasa.gov/', 'Science'], ['Nature Latest Research', 'https://www.nature.com/nature.rss', 'https://www.nature.com/', 'Science']] },
  entertainment: { neighbors: ['movies', 'streaming', 'music', 'hollywood', 'television', 'gaming'], sources: [['Variety Film & TV', 'https://variety.com/feed/', 'https://variety.com/', 'Entertainment'], ['Deadline Hollywood', 'https://deadline.com/feed/', 'https://deadline.com/', 'Entertainment']] },
  cricket: { neighbors: ['ipl', 'icc', 'test match', 'espncricinfo', 'cricbuzz', 'wisden', 'bcci'], sources: [['ESPNcricinfo News', 'https://www.espncricinfo.com/rss/content/story/feeds/0.xml', 'https://www.espncricinfo.com/', 'Sports'], ['BBC Sport Cricket', 'https://feeds.bbci.co.uk/sport/cricket/rss.xml', 'https://www.bbc.com/sport/cricket', 'Sports'], ['Cricbuzz Latest Headlines', 'https://www.cricbuzz.com/rss/news', 'https://www.cricbuzz.com/', 'Sports'], ['The Guardian Cricket', 'https://www.theguardian.com/sport/cricket/rss', 'https://www.theguardian.com/sport/cricket', 'Sports'], ['Wisden Cricket Weekly', 'https://wisden.substack.com/feed', 'https://wisden.com/', 'Newsletter']] },
  ai: { neighbors: ['ai agents', 'llms', 'openai', 'anthropic', 'langchain', 'mcp', 'machine learning'], sources: [['OpenAI News & Research', 'https://openai.com/news/rss.xml', 'https://openai.com/', 'Technology'], ['Anthropic Engineering Blog', 'https://www.anthropic.com/feed.xml', 'https://www.anthropic.com/', 'Technology'], ['MIT Technology Review AI', 'https://www.technologyreview.com/topic/artificial-intelligence/feed', 'https://www.technologyreview.com/', 'Technology'], ['Ars Technica AI & Science', 'https://feeds.arstechnica.com/arstechnica/index', 'https://arstechnica.com/', 'Technology']] },
  finance: { neighbors: ['markets', 'wall street', 'economy', 'fintech', 'crypto', 'stocks', 'investing'], sources: [['Wall Street Journal Markets', 'https://feeds.a.dj.com/rss/RSSMarketsMain.xml', 'https://www.wsj.com/', 'Finance'], ['Bloomberg Markets News', 'https://feeds.bloomberg.com/markets/news.rss', 'https://www.bloomberg.com/', 'Finance'], ['Financial Times Global Economy', 'https://www.ft.com/global-economy?format=rss', 'https://www.ft.com/', 'Finance'], ['CNBC Business & Finance', 'https://search.cnbc.com/rs/search/view.html?partnerId=2000&keywords=finance&sort=date&output=rss', 'https://www.cnbc.com/', 'Finance']] }
};
function findTopic(query) { const normalized = String(query || '').toLowerCase().trim(); return Object.keys(TOPIC_GRAPH).find((topic) => normalized === topic || normalized.includes(topic) || topic.includes(normalized) || TOPIC_GRAPH[topic].neighbors.some((item) => normalized.includes(item) || item.includes(normalized))); }
function expandSemanticNeighbors(query) { const topic = findTopic(query); return topic ? TOPIC_GRAPH[topic].neighbors.slice() : []; }
function topicGraphCandidates(query) { const topic = findTopic(query); if (!topic) return []; const value = TOPIC_GRAPH[topic]; return value.sources.map(([feed_name, feed_url, website_url, category]) => ({ feed_name, feed_url, website_url, category, topics: value.neighbors, source_engine: 'topic-graph', is_verified: false })); }
module.exports = { TOPIC_GRAPH, expandSemanticNeighbors, topicGraphCandidates };
